# Initial Setup #

In [20]:
import pandas as pd

In [21]:
df = pd.read_csv("C:/Users/kevin/Projects/fiji-event-engagement-analytics/data/raw/fiji_fall_event_preferences.csv")

In [22]:
df.shape     # how many rows, how many columns

(43, 17)

In [23]:
df.columns      # exact column names from the Google Form

Index(['Timestamp', 'Class Year',
       'How many chapter events would you say you attended last semester? (This includes everything from B.O.B. pregames to events like Senior Sendoff)',
       'Rank how likely you are to attend each type of event:    \n\nPregames (1 = NEVER, 5 = ALWAYS)',
       'Postgames  (1 = NEVER, 5 = ALWAYS)',
       'Socials/Mixers  (1 = NEVER, 5 = ALWAYS)',
       'Brotherhood Events (fam olympics, paintball, boat trip, etc.)\n(1 = NEVER, 5 = ALWAYS)',
       'Philanthropy/Fundraising Events  \n(1 = NEVER, 5 = ALWAYS)',
       'Professional/Networking Events\n(1 = NEVER, 5 = ALWAYS)',
       'Community Service Events\n(1 = NEVER, 5 = ALWAYS)',
       'Alumni Events (pig dinner, etc.)\n(1 = NEVER, 5 = ALWAYS)',
       'What day(s) for events work best for you? (Check all that apply)',
       'What's the #1 reason you'd skip an event?',
       'How do you usually hear about events?',
       'Given the circumstances, rate your satisfaction with the  Spring semester's event lineup. (1 = Unsatisfied, 5 = Very Satisfied)',
       'Optional: One event you wish we did that we haven't?',
       'Optional: If we did more community service, what type of service would actually interest you?'],
      dtype='str')

In [24]:
df.head()

,Timestamp,Class Year,How many chapter events would you say you attended last semester? (This includes everything from B.O.B. pregames to events like Senior Sendoff),"Rank how likely you are to attend each type of event: \n\nPregames (1 = NEVER, 5 = ALWAYS)","Postgames (1 = NEVER, 5 = ALWAYS)","Socials/Mixers (1 = NEVER, 5 = ALWAYS)","Brotherhood Events (fam olympics, paintball, boat trip, etc.)\n(1 = NEVER, 5 = ALWAYS)","Philanthropy/Fundraising Events \n(1 = NEVER, 5 = ALWAYS)","Professional/Networking Events\n(1 = NEVER, 5 = ALWAYS)","Community Service Events\n(1 = NEVER, 5 = ALWAYS)","Alumni Events (pig dinner, etc.)\n(1 = NEVER, 5 = ALWAYS)",What day(s) for events work best for you? (Check all that apply),What's the #1 reason you'd skip an event?,How do you usually hear about events?,"Given the circumstances, rate your satisfaction with the Spring semester's event lineup. (1 = Unsatisfied, 5 = Very Satisfied)",Optional: One event you wish we did that we haven't?,"Optional: If we did more community service, what type of service would actually interest you?"
0,7/20/2026 12:24:56,Rising Senior,10+,5,3,5,5,5,4,4,3,"Weekday evening, Friday, Saturday, Sunday",Too tired/burnt out,GroupMe (brotherchat/important announcements),4,Island Week,More animal shelter help
1,7/20/2026 12:33:20,Rising Senior,10+,4,4,4,5,4,3,3,5,"Weekday evening, Friday, Saturday, Sunday",Conflicts with class/work,GroupMe (brotherchat/important announcements),3,Dye tournament,NaN
2,7/20/2026 12:33:46,Rising Junior,10+,4,5,4,3,2,4,5,3,"Weekday evening, Friday, Saturday, Sunday",Too tired/burnt out,GroupMe (brotherchat/important announcements),4,NaN,NaN
3,7/20/2026 12:33:51,Rising Senior,10+,3,5,4,4,4,2,3,5,"Friday, Saturday, Sunday",Conflicts with class/work,In-person/word from other brothers,3,NaN,NaN
4,7/20/2026 12:33:53,Rising Junior,10+,4,4,4,3,3,4,2,3,"Weekday evening, Friday, Saturday",Not interested in event type,GroupMe (brotherchat/important announcements),3,NaN,NaN

# Data Cleaning / Prep #

In [25]:
# renaming columns for easier access
column_map = {
    'Timestamp': 'timestamp',
    'Class Year': 'class_year',
    'How many chapter events would you say you attended last semester? (This includes everything from B.O.B. pregames to events like Senior Sendoff)': 'events_attended',
    'Rank how likely you are to attend each type of event:    \n\nPregames (1 = NEVER, 5 = ALWAYS)': 'rating_pregames',
    'Postgames  (1 = NEVER, 5 = ALWAYS)': 'rating_postgames',
    'Socials/Mixers  (1 = NEVER, 5 = ALWAYS)': 'rating_socials',
    'Brotherhood Events (fam olympics, paintball, boat trip, etc.)\n(1 = NEVER, 5 = ALWAYS)': 'rating_brotherhood',
    'Philanthropy/Fundraising Events  \n(1 = NEVER, 5 = ALWAYS)': 'rating_philanthropy',
    'Professional/Networking Events\n(1 = NEVER, 5 = ALWAYS)': 'rating_professional',
    'Community Service Events\n(1 = NEVER, 5 = ALWAYS)': 'rating_community_service',
    'Alumni Events (pig dinner, etc.)\n(1 = NEVER, 5 = ALWAYS)': 'rating_alumni',
    'What day(s) for events work best for you? (Check all that apply)': 'preferred_days',
    "What's the #1 reason you'd skip an event?": 'reason_skip_event',
    'How do you usually hear about events?': 'event_communication',
    "Given the circumstances, rate your satisfaction with the  Spring semester's event lineup. (1 = Unsatisfied, 5 = Very Satisfied)": 'satisfaction_event_lineup',
    "Optional: One event you wish we did that we haven't?": 'wished_event',
    'Optional: If we did more community service, what type of service would actually interest you?': 'community_service_interest'
}

In [26]:
df = df.rename(columns=column_map)

In [27]:
df.columns

Index(['timestamp', 'class_year', 'events_attended', 'rating_pregames',
       'rating_postgames', 'rating_socials', 'rating_brotherhood',
       'rating_philanthropy', 'rating_professional',
       'rating_community_service', 'rating_alumni', 'preferred_days',
       'reason_skip_event', 'event_communication', 'satisfaction_event_lineup',
       'wished_event', 'community_service_interest'],
      dtype='str')

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   timestamp                   43 non-null     str
 1   class_year                  43 non-null     str
 2   events_attended             43 non-null     str
 3   rating_pregames             43 non-null     int64
 4   rating_postgames            43 non-null     int64
 5   rating_socials              43 non-null     int64
 6   rating_brotherhood          43 non-null     int64
 7   rating_philanthropy         43 non-null     int64
 8   rating_professional         43 non-null     int64
 9   rating_community_service    43 non-null     int64
 10  rating_alumni               43 non-null     int64
 11  preferred_days              43 non-null     str
 12  reason_skip_event           43 non-null     str
 13  event_communication         43 non-null     str
 14  satisfaction_event_lineup   43 non-null     int64
 15  wished_event                21 non-null     str
 16  community_service_interest  13 non-null     str
dtypes: int64(9), str(8)
memory usage: 5.8 KB

In [29]:
# Display value counts for categorical columns to understand the distribution of responses
for col in ['class_year', 'events_attended', 'preferred_days', 'reason_skip_event', 'event_communication']:
    print(col)
    print(df[col].value_counts())
    print()

class_year
class_year
Rising Sophomore    17
Rising Junior       15
Rising Senior       11
Name: count, dtype: int64

events_attended
events_attended
10+    29
7-9     6
4-6     4
0-3     4
Name: count, dtype: int64

preferred_days
preferred_days
Weekday evening, Friday, Saturday                               12
Weekday evening, Friday, Saturday, Sunday                        9
Friday, Saturday, Sunday                                         9
Weekday afternoon, Weekday evening, Friday, Saturday, Sunday     4
Weekday afternoon, Weekday evening, Friday, Saturday             3
Friday, Saturday                                                 3
Saturday, Sunday                                                 1
Weekday afternoon, Sunday                                        1
Weekday afternoon, Weekday evening, Saturday                     1
Name: count, dtype: int64

reason_skip_event
reason_skip_event
Conflicts with class/work       21
Not interested in event type    12
Too tired/burnt out              8
Cost                             1
Lazy af                          1
Name: count, dtype: int64

event_communication
event_communication
GroupMe (brotherchat/important announcements)    31
Chapter Meetings                                  8
In-person/word from other brothers                3
Personally texted from exec/committee members     1
Name: count, dtype: int64

In [30]:
# "Lazy af" was a free-text "Other" response. Folding it into "Too tired/burnt out" since it's semantically equivalent
# Judgement call: could have also kept as standalone "Other" category
df['reason_skip_event'] = df['reason_skip_event'].replace({'Lazy af': 'Too tired/burnt out'})

df['reason_skip_event'].value_counts()     # confirming merge was successful

reason_skip_event
Conflicts with class/work       21
Not interested in event type    12
Too tired/burnt out              9
Cost                             1
Name: count, dtype: int64

In [31]:
# preferred_days into 5 separate binary columns
day_dummies = df['preferred_days'].str.get_dummies(', ')
day_dummies.columns

Index(['Friday', 'Saturday', 'Sunday', 'Weekday afternoon', 'Weekday evening'], dtype='str')

In [32]:
# renaming dummy dolumns
day_dummies = day_dummies.rename(columns={
    'Weekday afternoon': 'pref_weekday_afternoon',
    'Weekday evening': 'pref_weekday_evening',
    'Friday': 'pref_friday',
    'Saturday': 'pref_saturday',
    'Sunday': 'pref_sunday'
})

df = pd.concat([df, day_dummies], axis=1)     # axis=1 is okay because row order and index remain the same
df.columns     # confirm 5 new pref_ columns are now attached

Index(['timestamp', 'class_year', 'events_attended', 'rating_pregames',
       'rating_postgames', 'rating_socials', 'rating_brotherhood',
       'rating_philanthropy', 'rating_professional',
       'rating_community_service', 'rating_alumni', 'preferred_days',
       'reason_skip_event', 'event_communication', 'satisfaction_event_lineup',
       'wished_event', 'community_service_interest', 'pref_friday',
       'pref_saturday', 'pref_sunday', 'pref_weekday_afternoon',
       'pref_weekday_evening'],
      dtype='str')

In [33]:
df.columns[df.columns.duplicated()]  # quick check; returns empty Index([]) if clean

Index([], dtype='str')

In [34]:
df[['preferred_days', 'pref_friday', 'pref_saturday', 'pref_sunday']].head()

,preferred_days,pref_friday,pref_saturday,pref_sunday
0,"Weekday evening, Friday, Saturday, Sunday",1,1,1
1,"Weekday evening, Friday, Saturday, Sunday",1,1,1
2,"Weekday evening, Friday, Saturday, Sunday",1,1,1
3,"Friday, Saturday, Sunday",1,1,1
4,"Weekday evening, Friday, Saturday",1,1,0

In [35]:
df.columns # make sure 22 columns now present and no duplicate columns

Index(['timestamp', 'class_year', 'events_attended', 'rating_pregames',
       'rating_postgames', 'rating_socials', 'rating_brotherhood',
       'rating_philanthropy', 'rating_professional',
       'rating_community_service', 'rating_alumni', 'preferred_days',
       'reason_skip_event', 'event_communication', 'satisfaction_event_lineup',
       'wished_event', 'community_service_interest', 'pref_friday',
       'pref_saturday', 'pref_sunday', 'pref_weekday_afternoon',
       'pref_weekday_evening'],
      dtype='str')

In [36]:
# One-hot encoding class_year
class_dummies = pd.get_dummies(df['class_year'], prefix='class')   # haven't picked a model yet, so no drop_first for now
class_dummies.head()

   class_Rising Junior  class_Rising Senior  class_Rising Sophomore
0                False                 True                   False
1                False                 True                   False
2                 True                False                   False
3                False                 True                   False
4                 True                False                   False

In [37]:
# merge into df
df = pd.concat([df, class_dummies], axis=1)

print(df.columns[df.columns.duplicated()])    # quick check; returns empty Index([]) if clean

Index([], dtype='str')

In [ ]:
df.columns    # 3 new class_ columns merged properly

Index(['timestamp', 'class_year', 'events_attended', 'rating_pregames',
       'rating_postgames', 'rating_socials', 'rating_brotherhood',
       'rating_philanthropy', 'rating_professional',
       'rating_community_service', 'rating_alumni', 'preferred_days',
       'reason_skip_event', 'event_communication', 'satisfaction_event_lineup',
       'wished_event', 'community_service_interest', 'pref_friday',
       'pref_saturday', 'pref_sunday', 'pref_weekday_afternoon',
       'pref_weekday_evening', 'class_Rising Junior', 'class_Rising Senior',
       'class_Rising Sophomore'],
      dtype='str')

In [39]:
# events_attendeed ordinal encoding
bucket_order = ['0-3', '4-6', '7-9', '10+']

df['events_attended'] = pd.Categorical(
    df['events_attended'],
    categories=bucket_order,
    ordered=True
)

df['events_attended'].dtype

CategoricalDtype(categories=['0-3', '4-6', '7-9', '10+'], ordered=True, categories_dtype=str)

In [41]:
# make events_attended numeric for modeling
df['events_attended_ordinal'] = df['events_attended'].cat.codes    # convert each category to its rank position as an int
df[['events_attended', 'events_attended_ordinal']].head(15)

   events_attended  events_attended_ordinal
0              10+                        3
1              10+                        3
2              10+                        3
3              10+                        3
4              10+                        3
5              10+                        3
6              10+                        3
7              10+                        3
8              10+                        3
9              7-9                        2
10             10+                        3
11             7-9                        2
12             4-6                        1
13             7-9                        2
14             10+                        3

In [ ]:
# reshaping using pd.melt to get 8 separate rows for each individual rating all 8 event types
rating_cols = ['rating_pregames', 'rating_postgames', 'rating_socials',
               'rating_brotherhood', 'rating_philanthropy', 'rating_professional',
               'rating_community_service', 'rating_alumni']

df_long = df.melt(
    id_vars = [col for col in df.columns if col not in rating_cols],
    value_vars = rating_cols,
    var_name = 'event_type',   # name of new column holding the type of event
    value_name = 'rating'      # name of the new column holding the rating value
)

df_long.shape

(344, 20)

In [48]:
df_long[['class_year', 'event_type', 'rating']].head(10)

         class_year       event_type  rating
0     Rising Senior  rating_pregames       5
1     Rising Senior  rating_pregames       4
2     Rising Junior  rating_pregames       4
3     Rising Senior  rating_pregames       3
4     Rising Junior  rating_pregames       4
5  Rising Sophomore  rating_pregames       4
6  Rising Sophomore  rating_pregames       4
7  Rising Sophomore  rating_pregames       5
8  Rising Sophomore  rating_pregames       4
9  Rising Sophomore  rating_pregames       5

In [ ]:
# see first response's ratings for all 8 event types
df_long[df_long['timestamp'] == df['timestamp'].iloc[0]][['event_type', 'rating']]

                   event_type  rating
0             rating_pregames       5
43           rating_postgames       3
86             rating_socials       5
129        rating_brotherhood       5
172       rating_philanthropy       5
215       rating_professional       4
258  rating_community_service       4
301             rating_alumni       3

In [52]:
# changing rating_ names back to reduce redundancy
df_long['event_type'] = df_long['event_type'].str.replace('rating_', '', regex=False)
df_long['event_type'].value_counts()

event_type
pregames             43
postgames            43
socials              43
brotherhood          43
philanthropy         43
professional         43
community_service    43
alumni               43
Name: count, dtype: int64

# EDA (also to help drive synthetic data creation decisions) #

In [53]:
# Group by class year AND event type, look at both the average rating 
# and how many people are in each group (determine if the average is trustworthy)
year_event_summary = df_long.groupby(['class_year', 'event_type'])['rating'].agg(['mean', 'count'])

year_event_summary

                                        mean  count
class_year       event_type
Rising Junior    alumni             3.466667     15
                 brotherhood        4.266667     15
                 community_service  3.133333     15
                 philanthropy       3.200000     15
                 postgames          4.000000     15
                 pregames           4.200000     15
                 professional       3.333333     15
                 socials            4.533333     15
Rising Senior    alumni             3.454545     11
                 brotherhood        3.636364     11
                 community_service  2.545455     11
                 philanthropy       2.909091     11
                 postgames          3.818182     11
                 pregames           3.363636     11
                 professional       3.272727     11
                 socials            4.090909     11
Rising Sophomore alumni             3.764706     17
                 brotherhood        4.294118     17
                 community_service  3.176471     17
                 philanthropy       3.470588     17
                 postgames          3.647059     17
                 pregames           3.941176     17
                 professional       4.117647     17
                 socials            4.764706     17

Quick Takeaways: 
- Rising seniors consistently rate most event categories lower than Juniors and Sophomores ("senioritis" perhaps)
- Sophomores tend to be the highest-rating group overall

In [55]:
# For each (class_year, event_type) group, get the proportion of people
# who gave each rating value (1-5)
rating_distributions = (
    df_long
    .groupby(['class_year', 'event_type'])['rating']
    .value_counts(normalize=True)
    .sort_index()
)

rating_distributions

class_year        event_type    rating
Rising Junior     alumni        1         0.066667
                                3         0.533333
                                4         0.200000
                                5         0.200000
                  brotherhood   2         0.066667
                                            ...
Rising Sophomore  professional  4         0.176471
                                5         0.470588
                  socials       3         0.058824
                                4         0.117647
                                5         0.823529
Name: proportion, Length: 97, dtype: float64

In [56]:
# Temporarily show all rows instead of truncating
with pd.option_context('display.max_rows', None):
    print(rating_distributions)

class_year        event_type         rating
Rising Junior     alumni             1         0.066667
                                     3         0.533333
                                     4         0.200000
                                     5         0.200000
                  brotherhood        2         0.066667
                                     3         0.133333
                                     4         0.266667
                                     5         0.533333
                  community_service  1         0.066667
                                     2         0.333333
                                     3         0.266667
                                     4         0.066667
                                     5         0.266667
                  philanthropy       1         0.066667
                                     2         0.133333
                                     3         0.466667
                                     4         0.200000
                                     5         0.133333
                  postgames          2         0.066667
                                     3         0.200000
                                     4         0.400000
                                     5         0.333333
                  pregames           3         0.133333
                                     4         0.533333
                                     5         0.333333
                  professional       1         0.066667
                                     2         0.133333
                                     3         0.400000
                                     4         0.200000
                                     5         0.200000
                  socials            3         0.066667
                                     4         0.333333
                                     5         0.600000
Rising Senior     alumni             2         0.363636
                                     3         0.181818
                                     4         0.090909
                                     5         0.363636
                  brotherhood        1         0.090909
                                     2         0.090909
                                     3         0.272727
                                     4         0.181818
                                     5         0.363636
                  community_service  1         0.272727
                                     2         0.090909
                                     3         0.454545
                                     4         0.181818
                  philanthropy       1         0.181818
                                     2         0.272727
                                     3         0.090909
                                     4         0.363636
                                     5         0.090909
                  postgames          1         0.090909
                                     3         0.181818
                                     4         0.454545
                                     5         0.272727
                  pregames           2         0.181818
                                     3         0.454545
                                     4         0.181818
                                     5         0.181818
                  professional       2         0.272727
                                     3         0.272727
                                     4         0.363636
                                     5         0.090909
                  socials            2         0.090909
                                     3         0.090909
                                     4         0.454545
                                     5         0.363636
Rising Sophomore  alumni             2         0.294118
                                     3         0.117647
                                     4         0.117647
                                     5         0.470588
                  brotherhood        3         0.058824
                                     4         0.588235
                                     5         0.352941
                  community_service  1         0.058824
                                     2         0.235294
                                     3         0.352941
                                     4         0.176471
                                     5         0.176471
                  philanthropy       2         0.235294
                                     3         0.294118
                                     4         0.235294
                                     5         0.235294
                  postgames          2         0.117647
                                     3         0.294118
                                     4         0.411765
                                     5         0.176471
                  pregames           2         0.058824
                                     3         0.176471
                                     4         0.529412
                                     5         0.235294
                  professional       3         0.352941
                                     4         0.176471
                                     5         0.470588
                  socials            3         0.058824
                                     4         0.117647
                                     5         0.823529
Name: proportion, dtype: float64

Some ratings were not selected at all. This doesn't necessarily mean 100% of the time, that group will never give that rating. But based on the small subset of responses, it is less likely. (Important to note this for building synthetic data generator)

In [57]:
# Isolate just one group's raw ratings, as actual 1-5 vote counts (not yet normalized)
senior_cs = df_long[
    (df_long['class_year'] == 'Rising Senior') & 
    (df_long['event_type'] == 'community_service')
]['rating']

# Raw counts per rating value, as they exist right now (rating 5 will be missing)
raw_counts = senior_cs.value_counts()
print("Before reindexing:")
print(raw_counts)

# Force it to include every rating 1-5, filling missing ones with 0
raw_counts_full = raw_counts.reindex([1, 2, 3, 4, 5], fill_value=0)
print("\nAfter reindexing:")
print(raw_counts_full)

Before reindexing:
rating
3    5
1    3
4    2
2    1
Name: count, dtype: int64

After reindexing:
rating
1    3
2    1
3    5
4    2
5    0
Name: count, dtype: int64

In [76]:
# Generalize previous code to all 24 groups
def smooth_probabilities(ratings, possible_values=[1, 2, 3, 4, 5], alpha = 0.3):   # decided this alpha based on personal experience
    """
    Takes a Series of raw rating values from one group,
    returns a Series of Laplace-smoothed probabilities for each possible rating.
    """
    counts = ratings.value_counts().reindex(possible_values, fill_value=0)
    smoothed = (counts + alpha) / (counts.sum() + alpha * len(possible_values))
    return smoothed

# Apply this function to every (class_year, event_type) group
smoothed_distributions = (
    df_long
    .groupby(['class_year', 'event_type'])['rating']
    .apply(smooth_probabilities)
)

In [77]:
# Quick check: how many rows total? Should be 24 groups × 5 ratings = 120
print(len(smoothed_distributions))

120

In [78]:
with pd.option_context('display.max_rows', None):
    print(smoothed_distributions)

class_year        event_type         (Rising Junior, alumni)
Rising Junior     alumni             1                          0.078788
                                     2                          0.018182
                                     3                          0.503030
                                     4                          0.200000
                                     5                          0.200000
                  brotherhood        1                          0.018182
                                     2                          0.078788
                                     3                          0.139394
                                     4                          0.260606
                                     5                          0.503030
                  community_service  1                          0.078788
                                     2                          0.321212
                                     3                          0.260606
                                     4                          0.078788
                                     5                          0.260606
                  philanthropy       1                          0.078788
                                     2                          0.139394
                                     3                          0.442424
                                     4                          0.200000
                                     5                          0.139394
                  postgames          1                          0.018182
                                     2                          0.078788
                                     3                          0.200000
                                     4                          0.381818
                                     5                          0.321212
                  pregames           1                          0.018182
                                     2                          0.018182
                                     3                          0.139394
                                     4                          0.503030
                                     5                          0.321212
                  professional       1                          0.078788
                                     2                          0.139394
                                     3                          0.381818
                                     4                          0.200000
                                     5                          0.200000
                  socials            1                          0.018182
                                     2                          0.018182
                                     3                          0.078788
                                     4                          0.321212
                                     5                          0.563636
Rising Senior     alumni             1                          0.024000
                                     2                          0.344000
                                     3                          0.184000
                                     4                          0.104000
                                     5                          0.344000
                  brotherhood        1                          0.104000
                                     2                          0.104000
                                     3                          0.264000
                                     4                          0.184000
                                     5                          0.344000
                  community_service  1                          0.264000
                                     2                          0.104000
                                     3                          0.424000
                                     4                          0.184000
                                     5                          0.024000
                  philanthropy       1                          0.184000
                                     2                          0.264000
                                     3                          0.104000
                                     4                          0.344000
                                     5                          0.104000
                  postgames          1                          0.104000
                                     2                          0.024000
                                     3                          0.184000
                                     4                          0.424000
                                     5                          0.264000
                  pregames           1                          0.024000
                                     2                          0.184000
                                     3                          0.424000
                                     4                          0.184000
                                     5                          0.184000
                  professional       1                          0.024000
                                     2                          0.264000
                                     3                          0.264000
                                     4                          0.344000
                                     5                          0.104000
                  socials            1                          0.024000
                                     2                          0.104000
                                     3                          0.104000
                                     4                          0.424000
                                     5                          0.344000
Rising Sophomore  alumni             1                          0.016216
                                     2                          0.286486
                                     3                          0.124324
                                     4                          0.124324
                                     5                          0.448649
                  brotherhood        1                          0.016216
                                     2                          0.016216
                                     3                          0.070270
                                     4                          0.556757
                                     5                          0.340541
                  community_service  1                          0.070270
                                     2                          0.232432
                                     3                          0.340541
                                     4                          0.178378
                                     5                          0.178378
                  philanthropy       1                          0.016216
                                     2                          0.232432
                                     3                          0.286486
                                     4                          0.232432
                                     5                          0.232432
                  postgames          1                          0.016216
                                     2                          0.124324
                                     3                          0.286486
                                     4                          0.394595
                                     5                          0.178378
                  pregames           1                          0.016216
                                     2                          0.070270
                                     3                          0.178378
                                     4                          0.502703
                                     5                          0.232432
                  professional       1                          0.016216
                                     2                          0.016216
                                     3                          0.340541
                                     4                          0.178378
                                     5                          0.448649
                  socials            1                          0.016216
                                     2                          0.016216
                                     3                          0.070270
                                     4                          0.124324
                                     5                          0.772973
Name: rating, dtype: float64

In [83]:
# Raw counts of yes/no for all 5 day columns
day_columns = ['pref_friday', 'pref_saturday', 'pref_sunday', 'pref_weekday_afternoon', 'pref_weekday_evening']

for col in day_columns:
    print(col)
    print(df_long[col].value_counts())
    print()

pref_friday
pref_friday
1    320
0     24
Name: count, dtype: int64

pref_saturday
pref_saturday
1    336
0      8
Name: count, dtype: int64

pref_sunday
pref_sunday
1    192
0    152
Name: count, dtype: int64

pref_weekday_afternoon
pref_weekday_afternoon
0    272
1     72
Name: count, dtype: int64

pref_weekday_evening
pref_weekday_evening
1    232
0    112
Name: count, dtype: int64

Dividing each by 8 to determine actual people yields these results:
- Friday --> 40 yes, 3 no
- Saturday --> 42 yes, 1 no
- Sunday --> 24 yes, 19 no
- Weekday afternoon --> 9 yes, 34 no
- Weekday evening --> 29 yes, 14 no

Friday and Saturday can't be used as a comparison lever (Just a fact to try and to events Friday/Saturday)

In [84]:
# Mean/count on two strongest candidates (sunday and weekday evening)
sunday_summary = df_long.groupby(['pref_sunday', 'event_type'])['rating'].agg(['mean', 'count'])
evening_summary = df_long.groupby(['pref_weekday_evening', 'event_type'])['rating'].agg(['mean', 'count'])

print(sunday_summary)
print()
print(evening_summary)

                                   mean  count
pref_sunday event_type
0           alumni             3.842105     19
            brotherhood        4.000000     19
            community_service  3.000000     19
            philanthropy       3.263158     19
            postgames          4.052632     19
            pregames           3.894737     19
            professional       3.631579     19
            socials            4.736842     19
1           alumni             3.375000     24
            brotherhood        4.208333     24
            community_service  3.000000     24
            philanthropy       3.208333     24
            postgames          3.625000     24
            pregames           3.875000     24
            professional       3.625000     24
            socials            4.333333     24

                                            mean  count
pref_weekday_evening event_type
0                    alumni             3.642857     14
                     brotherhood        4.142857     14
                     community_service  3.214286     14
                     philanthropy       3.142857     14
                     postgames          3.857143     14
                     pregames           3.857143     14
                     professional       3.428571     14
                     socials            4.142857     14
1                    alumni             3.551724     29
                     brotherhood        4.103448     29
                     community_service  2.896552     29
                     philanthropy       3.275862     29
                     postgames          3.793103     29
                     pregames           3.896552     29
                     professional       3.724138     29
                     socials            4.689655     29

Day-of-week preference does not show a consistent relationship with event-type ratings, unlike class year

In [86]:
# Checking skip event and event type relationship
# What are the categories and how many people are in each
print(df_long['reason_skip_event'].value_counts())

reason_skip_event
Conflicts with class/work       168
Not interested in event type     96
Too tired/burnt out              72
Cost                              8
Name: count, dtype: int64

Dividing each by 8 to determine actual people yields these results:
- Conflicts with class/work --> 21 
- Not interested in event type --> 12
- Too tired/burnt out --> 9
- Cost --> 1

In [87]:
skip_reason_summary = df_long.groupby(['reason_skip_event', 'event_type'])['rating'].agg(['mean', 'count'])
skip_reason_summary

                                                    mean  count
reason_skip_event            event_type
Conflicts with class/work    alumni             4.047619     21
                             brotherhood        4.428571     21
                             community_service  3.333333     21
                             philanthropy       3.904762     21
                             postgames          4.142857     21
                             pregames           3.857143     21
                             professional       3.714286     21
                             socials            4.571429     21
Cost                         alumni             2.000000      1
                             brotherhood        4.000000      1
                             community_service  3.000000      1
                             philanthropy       3.000000      1
                             postgames          4.000000      1
                             pregames           4.000000      1
                             professional       3.000000      1
                             socials            5.000000      1
Not interested in event type alumni             3.416667     12
                             brotherhood        3.833333     12
                             community_service  2.333333     12
                             philanthropy       2.500000     12
                             postgames          3.083333     12
                             pregames           3.916667     12
                             professional       3.500000     12
                             socials            4.416667     12
Too tired/burnt out          alumni             2.888889      9
                             brotherhood        3.777778      9
                             community_service  3.111111      9
                             philanthropy       2.666667      9
                             postgames          4.000000      9
                             pregames           3.888889      9
                             professional       3.666667      9
                             socials            4.444444      9

- Those not interested in event type vs. conflicts with class/work have lower ratings in 7 of the 8 event types
- Those too tired/burnt out vs. conflicts with class/work have lower ratings in 5 of the 8 event types

In [88]:
# Checking the distribution of attendance across different ordinal buckets
# how many people fall into each attendance bucket
print(df_long['events_attended_ordinal'].value_counts())

events_attended_ordinal
3    232
2     48
1     32
0     32
Name: count, dtype: int64

Dividing each by 8 to determine actual people yields these results:
- 0-3 --> 4
- 4-6 --> 4
- 7-9 --> 6
- 10+ --> 29

In [89]:
attendance_summary = df_long.groupby(['events_attended_ordinal', 'event_type'])['rating'].agg(['mean', 'count'])
attendance_summary

                                               mean  count
events_attended_ordinal event_type
0                       alumni             3.250000      4
                        brotherhood        2.500000      4
                        community_service  1.500000      4
                        philanthropy       2.000000      4
                        postgames          3.500000      4
                        pregames           3.500000      4
                        professional       3.000000      4
                        socials            4.500000      4
1                       alumni             4.250000      4
                        brotherhood        4.500000      4
                        community_service  3.750000      4
                        philanthropy       4.000000      4
                        postgames          3.500000      4
                        pregames           3.250000      4
                        professional       4.250000      4
                        socials            4.250000      4
2                       alumni             4.000000      6
                        brotherhood        4.166667      6
                        community_service  2.166667      6
                        philanthropy       3.166667      6
                        postgames          3.333333      6
                        pregames           4.000000      6
                        professional       3.833333      6
                        socials            4.500000      6
3                       alumni             3.448276     29
                        brotherhood        4.275862     29
                        community_service  3.275862     29
                        philanthropy       3.310345     29
                        postgames          4.000000     29
                        pregames           4.000000     29
                        professional       3.586207     29
                        socials            4.551724     29

Not enough sample and valid evidence to determine that events_attended_ordinal is a notable lever to acknowledge.

In [90]:
# reason_skip_event smoothed distribution
skip_reason_distributions = (
    df_long
    .groupby(['reason_skip_event', 'event_type'])['rating']
    .apply(smooth_probabilities)
)

skip_reason_distributions

reason_skip_event          event_type  (Conflicts with class/work, alumni)
Conflicts with class/work  alumni      1                                      0.013333
                                       2                                      0.057778
                                       3                                      0.368889
                                       4                                      0.057778
                                       5                                      0.502222
                                                                                ...
Too tired/burnt out        socials     1                                      0.028571
                                       2                                      0.028571
                                       3                                      0.219048
                                       4                                      0.123810
                                       5                                      0.600000
Name: rating, Length: 160, dtype: float64

In [91]:
# Overall (dataset-wide) smoothed distribution per event_type — used as fallback for Cost
overall_distributions = (
    df_long
    .groupby(['event_type'])['rating']
    .apply(smooth_probabilities)
)

overall_distributions

event_type         alumni
alumni             1         0.029213
                   2         0.208989
                   3         0.276404
                   4         0.141573
                   5         0.343820
brotherhood        1         0.029213
                   2         0.051685
                   3         0.141573
                   4         0.366292
                   5         0.411236
community_service  1         0.119101
                   2         0.231461
                   3         0.343820
                   4         0.141573
                   5         0.164045
philanthropy       1         0.074157
                   2         0.208989
                   3         0.298876
                   4         0.253933
                   5         0.164045
postgames          1         0.029213
                   2         0.074157
                   3         0.231461
                   4         0.411236
                   5         0.253933
pregames           1         0.006742
                   2         0.074157
                   3         0.231461
                   4         0.433708
                   5         0.253933
professional       1         0.029213
                   2         0.119101
                   3         0.343820
                   4         0.231461
                   5         0.276404
socials            1         0.006742
                   2         0.029213
                   3         0.074157
                   4         0.276404
                   5         0.613483
Name: rating, dtype: float64

# Synthetic Data Generation #

In [92]:
def blend_distributions(class_year, skip_reason, event_type, weight_class_year=0.65):
    """
    Combines the class_year distribution and reason_skip_event distribution
    for a given event_type into one final probability distribution.
    Falls back to the overall (event_type-only) distribution if skip_reason is 'Cost'.
    """
    class_year_dist = smoothed_distributions[class_year, event_type]

    if skip_reason == 'Cost':
        skip_dist = overall_distributions[event_type]
    else:
        skip_dist = skip_reason_distributions[skip_reason, event_type]

    weight_skip = 1 - weight_class_year
    final_dist = (weight_class_year * class_year_dist) + (weight_skip * skip_dist)

    return final_dist

In [93]:
# Test on example
test_result = blend_distributions('Rising Senior', 'Not interested in event type', 'community_service')
print(test_result)
print(test_result.sum())  # sanity check — should be very close to 1.0

(Rising Junior, alumni)
1    0.283081
2    0.153156
3    0.361156
4    0.153304
5    0.049304
Name: rating, dtype: float64
1.0